spring.application.name=LocalDeComidas

#configuracion dc la coneccion hacia la BD
spring.datasource.url=jdbc:h2:mem:comidas_bd
spring.datasource.username=sa
spring.datasource.password=

#activando el JPA
spring.jpa.hibernate.ddl-auto=create